crawler:
  linkPoolSize: 10
  imagePoolSize: 5
spring:
  application:
    name: WebScraper
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
